version: "3.8"

services:
  postgres:
    image: postgres
    container_name: postgres_stms
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
